package com.arshita.networktrafficanalyzer.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a security alert generated by the ThreatEngine.
 * Stored locally so the user can review historical alerts.
 */
@Entity(tableName = "security_alerts")
data class SecurityAlert(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /** Name of the app that triggered the alert. */
    val appName: String,

    /** Severity level: "LOW", "MEDIUM", "HIGH", or "CRITICAL". */
    val severity: String,

    /** Human-readable description of what was detected. */
    val description: String,

    /** Epoch millis when the alert was generated. */
    val timestamp: Long = System.currentTimeMillis()
)
